config/routes.rb
FinalApp::Application.routes.draw do
  root 'users#newsfeed'
  get "shared/_error_messages"

  get "friendships/find"

  get "friendships/create"

  get "friendships/new"

  resources :session, only: [:new, :create, :destroy]
  match '/login',  to: 'session#new',   via: 'get'
  match '/login', to: 'session#create', via: 'post'
  match '/login',  to: 'session#destroy',   via: 'delete'
  resources :users, :except => [:edit, :destroy, :index]
  match '/register',  to: 'users#new',   via: 'get'
  match '/newsfeed', to: 'users#newsfeed', via: 'get'
  match '/findfriends', to: 'friendships#find', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'
  resources :posts
  match '/posts',  to: 'posts#create',   via: 'post'
  match '/posts',  to: 'posts#destroyall',   via: 'delete'
  resources :friendships, :except => [:show, :edit, :index]

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :require_login
  def new
	end

  	def create
    user = User.find_by_email(params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
	    	# Sign the user in and redirect to the user's show page.
	     	sign_in user
      	redirect_to newsfeed_path
	    else
	    	# Create an error message and re-render the signin form.
	    	flash[:failed] = true
        redirect_to login_path
	  	end
  	end

  	def destroy
  		current_user = nil
	    sign_out
	    redirect_to login_path
  	end
end

app/helpers/session_helper.rb
module SessionHelper
	def sign_in(user)
	    remember_token = User.new_remember_token
	    cookies.permanent[:remember_token] = {value: remember_token,
                                            expires: 1.month.from_now.utc}
	    user.update_attribute(:remember_token, User.hash(remember_token))
	    self.current_user = user
  	end
  	def current_user=(user)
    	@current_user = user
 	end
  	def current_user
    	remember_token = User.hash(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end
    def signed_in?
      !current_user.nil?
    end

    def sign_out
      current_user.update_attribute(:remember_token,
                                    User.hash(User.new_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
    end
end

app/views/session/new.html.erb
<h1>Login</h1>
<div>
    <% if (flash[:failed]==true) then %>
        <h2 id="error">
            Login Failed
            <br>
            Invalid email/password combination
        </h2>
    <% end%>
    <% if (flash[:success] != nil) then %>
        <h2 id="good">
             Register Successful!
        </h2>
    <% end%>
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <br>
      <%= f.submit "Login" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", register_path %></p>
</div>