config/routes.rb
FinalApp::Application.routes.draw do
  root 'users#newsfeed'
  get "shared/_error_messages"

  get "friendships/find"

  get "friendships/create"

  get "friendships/new"

  resources :session, only: [:new, :create, :destroy]
  match '/login',  to: 'session#new',   via: 'get'
  match '/login', to: 'session#create', via: 'post'
  match '/login',  to: 'session#destroy',   via: 'delete'
  resources :users, :except => [:edit, :destroy, :index]
  match '/register',  to: 'users#new',   via: 'get'
  match '/newsfeed', to: 'users#newsfeed', via: 'get'
  match '/findfriends', to: 'friendships#find', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'
  resources :posts
  match '/posts',  to: 'posts#create',   via: 'post'
  match '/posts',  to: 'posts#destroyall',   via: 'delete'
  resources :friendships, :except => [:show, :edit, :index]

end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _error_messages
  end
end

app/views/shared/_error_messages.html.erb
<% if @user != nil and @user.errors.any? %>
    <h2 id="error">
    <% if @update != nil %>
        Update Failed!
    <% else %>
        Register Failed!
    <% end %>
    </h2>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
</div>
<% end %>

<% if @post != nil and @post.errors.any? %>
    <h2 id="error">
        Posting Failed!
    </h2>
  <div id="error_explanation">
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_friend_request.html.erb
  <%if !profile  %>
<%=  link_to image_tag("#{user.picture}" , alt: "#{user.id}", width: "40", height: "25"), user_path(user)%>
    <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
    <%end%>
    <br>
        <% status =  Friendship.friendship_status(current_user.id, user.id)  %>
        <% request = Friendship.where(sender_id: current_user.id, receiver_id: user.id).first(1)[0]%>
        <% if request == nil %>
            <% request = Friendship.where(sender_id: user.id, receiver_id: current_user.id).first(1)[0]%>
        <% end %>

         <% if status == "yourself" %>
            This is you!
        <% elsif status == "friends" %>
            Already Friends!
            <%= button_to "Delete!", friendship_path(request), :method => :delete %>
         <% elsif status == "sent" %>
            Friend request sent!
             <%= button_to "Unsend!", friendship_path(request), :method => :delete %>
         <% elsif status == "received" %>
            <%= button_to "Accept!", friendship_path(request), :method => :patch %>
            <%= button_to "Reject!", friendship_path(request), :method => :delete %>
        <% elsif status == "notfriends" %>
        <%= form_tag(friendship_path(request), method: "post") do %>
            <%= hidden_field_tag(:receiver_id, "#{user.id}") %>
            <%= hidden_field_tag(:sender_id, "#{current_user.id}") %>
            <%= hidden_field_tag(:status, "pending") %>
        <%= submit_tag("Add #{user.first_name} #{user.last_name}")%>
        <%end %>

    <% end %>

app/views/shared/_wall.html.erb
<% if @posts != nil %>
<%= render 'shared/error_messages' %>
<div id="wall">
<%= form_tag(posts_path, method: "post") do %>
  <%= label :content , "Post Here!"%>
  <br>
  <%= text_area_tag(:content) %>
  <% receiverId = 0 %>
  <% if @user != nil %>
  	<% receiverId = @user.id %>
  <% end %>
  <%= hidden_field_tag(:receiver_id, "#{receiverId}") %>
  <%= hidden_field_tag(:sender_id, "#{current_user.id}") %>
  <br>
  <%= submit_tag("Submit")%>
  </p>
<%end %>


<%postNum = 1%>
<% @posts.each do |post| %>
	<% user = User.find(post.sender_id) %>
	<%=  link_to image_tag("#{user.picture}" , alt: "WallPost#{postNum}", width: "40", height: "25"), user_path(user)%>

	<%= link_to "#{user.first_name} #{user.last_name}:", user_path(user) %>
	<br>

	<%= post.content %>
	<% postNum+=1%>
	<br>
	<font size ="1">
	<%= "#{post.created_at}" %>
	</font>
	</p>
	 <% end %>
	</div>
	<%else %>
		<%= "You can only see the profile wall of your Friend's" %>
	<%end %>