config/routes.rb
FinalApp::Application.routes.draw do
  root 'users#newsfeed'
  get "shared/_error_messages"

  get "friendships/find"

  get "friendships/create"

  get "friendships/new"

  resources :session, only: [:new, :create, :destroy]
  match '/login',  to: 'session#new',   via: 'get'
  match '/login', to: 'session#create', via: 'post'
  match '/login',  to: 'session#destroy',   via: 'delete'
  resources :users, :except => [:edit, :destroy, :index]
  match '/register',  to: 'users#new',   via: 'get'
  match '/newsfeed', to: 'users#newsfeed', via: 'get'
  match '/findfriends', to: 'friendships#find', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'
  resources :posts
  match '/posts',  to: 'posts#create',   via: 'post'
  match '/posts',  to: 'posts#destroyall',   via: 'delete'
  resources :friendships, :except => [:show, :edit, :index]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>MyBook | <%= yield(:title) %> </title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>
<header class="mainheader">
<div class="mainheader">
<%= link_to image_tag("MyBookBanner.png", alt: "Welcome to MyBook"), newsfeed_path %>
</div>
</header>


<% if signed_in? %>
<div   class="container"  >
<div id="sidebar">
<%= link_to image_tag("#{current_user.picture}" , alt: "Sidebar Picture", width: "80", height: "50"), user_path(current_user) %>
<% unless @requestMessage.nil? %>
<br>
<font size ="2">
<%= link_to "#{@requestMessage}",     preferences_path %>
<% end %>
</font>
<li><%= link_to "Find Friends",    findfriends_path %></li>
<li>
<%= link_to "Preferences " ,     preferences_path %>
</li>
<li><%= link_to "Logout",     login_path, :method => :delete %></li>
</div>
<% end %>


<div id="content">
<%= yield %>
</div>
<div id="footer">
<p> MyBook was created as a student project for CSCI 3308. It was developed in Ruby on Rails. </p>
</div>
</div>
</body>
</html>